#!/usr/bin/env bash
# claude-session-bootstrap.sh — auto-resolve tickvault runtime endpoints for
# every Claude Code session (Mac local, AWS remote, or claude.ai sandbox).
#
# Outputs:
#   .claude/.session-env      Shell-sourceable export block for the MCP server
#                             and any tool that wants TICKVAULT_*_URL env vars.
#
# Contract:
#   - Reads the active profile from config/claude-mcp-endpoints.toml.
#   - Auto-detects Docker (local profile) vs tunnel (mac-dev/aws-prod) when
#     the active profile is reachable; falls back to config value otherwise.
#   - Probes each endpoint with a 2s HEAD request and records REACHABLE / OFFLINE.
#   - Never fails the session — a dead endpoint just means MCP tools return
#     "not reachable" instead of breaking the shell.
#   - Idempotent. Safe to run on every SessionStart and PreCompact.

set -uo pipefail

CWD="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$CWD" || exit 0

CONFIG="$CWD/config/claude-mcp-endpoints.toml"
OUT="$CWD/.claude/.session-env"

if [ ! -f "$CONFIG" ]; then
    echo "bootstrap: $CONFIG missing — nothing to export" >&2
    exit 0
fi

PROFILE="${TICKVAULT_MCP_PROFILE:-}"
if [ -z "$PROFILE" ]; then
    PROFILE=$(awk -F'"' '/^active[[:space:]]*=/ { print $2; exit }' "$CONFIG")
fi
if [ -z "$PROFILE" ]; then
    PROFILE="local"
fi

read_profile_key() {
    local key="$1"
    awk -v section="[profiles.$PROFILE]" -v key="$key" '
        $0 == section { in_section = 1; next }
        /^\[/ { in_section = 0 }
        in_section && $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            gsub(/^[^=]*=[[:space:]]*"/, "")
            gsub(/"[[:space:]]*$/, "")
            print
            exit
        }
    ' "$CONFIG"
}

PROM=$(read_profile_key prometheus_url)
ALERT=$(read_profile_key alertmanager_url)
QDB=$(read_profile_key questdb_url)
GRAF=$(read_profile_key grafana_url)
API=$(read_profile_key tickvault_api_url)
LOGS_SRC=$(read_profile_key logs_source)
LOGS_DIR=$(read_profile_key logs_dir_local)

probe() {
    local url="$1"
    [ -z "$url" ] && { echo UNSET; return; }
    if curl -fsS -m 2 -o /dev/null "$url" 2>/dev/null; then
        echo REACHABLE
    else
        echo OFFLINE
    fi
}

PROM_S=$(probe "$PROM")
ALERT_S=$(probe "$ALERT")
QDB_S=$(probe "$QDB/status" 2>/dev/null || echo OFFLINE)
GRAF_S=$(probe "$GRAF/api/health" 2>/dev/null || echo OFFLINE)
API_S=$(probe "$API/health" 2>/dev/null || echo OFFLINE)

cat > "$OUT" <<EOF
# auto-generated by scripts/claude-session-bootstrap.sh
# profile: $PROFILE       generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
export TICKVAULT_MCP_PROFILE="$PROFILE"
export TICKVAULT_PROMETHEUS_URL="$PROM"
export TICKVAULT_ALERTMANAGER_URL="$ALERT"
export TICKVAULT_QUESTDB_URL="$QDB"
export TICKVAULT_GRAFANA_URL="$GRAF"
export TICKVAULT_API_URL="$API"
export TICKVAULT_LOGS_DIR="$LOGS_DIR"
export TICKVAULT_LOGS_SOURCE="$LOGS_SRC"
# probe snapshot (REACHABLE|OFFLINE|UNSET) — consumed by session-sanity.sh
export TICKVAULT_PROM_STATUS="$PROM_S"
export TICKVAULT_ALERT_STATUS="$ALERT_S"
export TICKVAULT_QDB_STATUS="$QDB_S"
export TICKVAULT_GRAF_STATUS="$GRAF_S"
export TICKVAULT_API_STATUS="$API_S"
EOF

echo "bootstrap: profile=$PROFILE  prom=$PROM_S  qdb=$QDB_S  graf=$GRAF_S  api=$API_S" >&2
exit 0
